package kr.co.donghyun.pinglauncher.presentation.util.dns

import android.content.Context
import android.net.ConnectivityManager
import android.util.Log
import kr.co.donghyun.pinglauncher.presentation.util.hosts.HostsManager
import java.io.File

/**
 * 두 가지 네트워크 후킹을 담당:
 *  1) /etc/resolv.conf  — JDK 의 JNDI DNS (SRV 레코드 조회) 용
 *  2) /etc/hosts        — Hamachi/LAN 등 수동 호스트네임→IP 매핑용
 *
 * 호출 순서: libpojavexec 로드 → setup() → JVM 부팅
 */
object DnsHookNative {
    private const val TAG = "DnsHookNative"

    // KR 도메인 SRV 해석에 friendly 한 DNS 들 (Cloudflare/Google + KT/SK)
    private val FALLBACK = listOf(
        "1.1.1.1",         // Cloudflare
        "8.8.8.8",         // Google
        "168.126.63.1",    // KT (KR)
        "168.126.63.2",    // KT (KR)
        "210.220.163.82",  // SK Broadband (KR)
    )

    @JvmStatic external fun installResolvConfRedirect(path: String)
    @JvmStatic external fun installHostsRedirect(path: String)

    fun setup(context: Context) {
        setupResolvConf(context)
        setupHosts(context)
    }

    private var activeDnsServers: List<String> = FALLBACK

    fun getActiveDnsServers(): List<String> = activeDnsServers


    private fun setupResolvConf(context: Context) {
        // 시스템 DNS + KR 폴백을 합쳐서 다양성 확보. 중복 제거.
        val systemDns = queryAndroidDnsServers(context)
        activeDnsServers = (systemDns + FALLBACK).distinct() // 목록 업데이트

        Log.d(TAG, "사용할 DNS 서버: $activeDnsServers")
        val resolvConf = File(context.cacheDir, "resolv.conf")
        resolvConf.writeText(buildString {
            append("# auto-generated by PingLauncher\n")
            append("options ndots:1 timeout:5 attempts:3\n")
            activeDnsServers.forEach { append("nameserver ").append(it).append('\n') }
        })

        Log.d(TAG, "resolv.conf 작성: ${resolvConf.absolutePath}")

        try {
            installResolvConfRedirect(resolvConf.absolutePath)
        } catch (e: UnsatisfiedLinkError) {
            Log.e(TAG, "installResolvConfRedirect 바인딩 실패 — libpojavexec.so 미로드?", e)
        }
    }

    private fun setupHosts(context: Context) {
        val hostsFile = HostsManager.buildHostsFile(context)
        Log.d(TAG, "hosts 작성: ${hostsFile.absolutePath} (${hostsFile.length()}B)")

        try {
            installHostsRedirect(hostsFile.absolutePath)
        } catch (e: UnsatisfiedLinkError) {
            Log.e(TAG, "installHostsRedirect 바인딩 실패 — 네이티브 미빌드?", e)
        }
    }

    private fun queryAndroidDnsServers(context: Context): List<String> {
        return try {
            val cm = context.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager
            val network = cm.activeNetwork ?: return emptyList()
            val lp = cm.getLinkProperties(network) ?: return emptyList()
            lp.dnsServers.mapNotNull { addr ->
                addr.hostAddress?.takeIf {
                    !it.startsWith("fe80:") && !it.contains("%")
                }
            }
        } catch (e: Exception) {
            Log.w(TAG, "Android DNS 조회 실패: ${e.message}")
            emptyList()
        }
    }
}